### ISSUE TITLE
after nuxt 3.6.5, nuxt-mapbox is not compatible 

### ISSUE THREAD

**Issue by llallallall** [AlexLavoie42/Nuxt-Mapbox#72] opened 2023-10-29 08:02 UTC
An error occurs like below

This module cannot be imported in the Vue part of your app. [importing @nuxt/kit from node_modules/nuxt-mapbox/dist/module.mjs?v=f57ae0f1]

until nuxt 3.6.5, it's working
tested) rm -rf .nuxt node_modules  && npm install nuxt@3.6.5  --save-exact  && npm install nuxt-mapbox &&  npm run dev

{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "mapbox-gl": "^2.15.0",
    "nuxt": "3.6.5",
    "vue": "^3.3.7",
    "vue-router": "^4.2.5"
  },
  "dependencies": {
    "nuxt-mapbox": "^1.4.5-1"
  }
}

**Comment by volkipp** [comment] 2023-10-30 17:41
Thanks for identifying the last working version! I'm running into the same issue

**Comment by AlexLavoie42** [comment] 2023-10-30 18:03
Could you please provide a reproduction using [the playground](https://stackblitz.com/edit/github-kv3c1q?file=playground%2Fpages%2Findex.vue)?

I have been running the module in production using the latest Nuxt version (v3.8.0) and I've had no such issue.

**Comment by AlexLavoie42** [comment] 2023-10-30 19:50
Make sure you are also using the latest version of typescript. I was getting similar errors in CI that was caused by an old version of typescript being used.

**Comment by AlexLavoie42** [comment] 2023-11-01 01:41
Closing this for now as I have updated the module to Nuxt 3.8.0 with #73

**Closed by AlexLavoie42** 2023-11-01 01:41 UTC
